### ISSUE TITLE
bacula is gone

### ISSUE THREAD

**Issue by samweisgamdschie** [freenas/iocage-ix-plugins#227]
According to commit d6e24e70c0aa1faa6b8086a8275f72d7575ea336 bacula was removed because it is broken. What does that mean for already installed instances (what I have!)? Do I have to migrate?  Will it come back? Are there other ways to install bacula within freenas?

**Comment by kmoore134** [comment]
It may end up coming back to our community repo (once somebody fixes it)

https://github.com/ix-plugin-hub/iocage-plugin-index/

You may need to re-install it at that point, however you can still safely use the installed plugin. It won't get removed.

You can also create a generic FreeBSD Jail and install it manually if the plugin isn't fixed in a timely manner.
