### ISSUE TITLE
Plex Server Update

### ISSUE THREAD

**Issue by victor7376** [freenas/iocage-ix-plugins#264]
I keep receiving a message to update but the official Plex server plugin is still showing as the old version.

I’ve tried a few guides to manual update but non work for me.

**Comment by Legion495** [comment]
Same but did not try anything other than running a package update once.

**Comment by MTCoster** [comment]
Any updates on this? The last time a Plex Server update was requested, the feedback was:

> The packages for Plex on BSD tend to lag 3-7 days behind what plex will start notifying about. However once they are available, in the FreeNAS UI you should be able to do the upgrade.

_Originally posted by @kmoore134 in https://github.com/freenas/iocage-ix-plugins/issues/231#issuecomment-622412451_

The current version available from this repo is 1.21.1.3876 (released [2020-01-06](https://forums.plex.tv/t/plex-media-server/30447/389)). There have been four releases to the main update channel since then. What happened to 3-7 days behind?

**Comment by kmoore134** [comment]
Odd, because I see the port has been updated here. I'll look further, but first, what version of TrueNAS are you on?

**Comment by MTCoster** [comment]
I'm running `TrueNAS-12.0-U1.1` - just seen `U2` is available, so I'll try updating to that before anything else.

**Comment by victor7376** [comment]
I’ve been doing manual updates for mine as it seems TrueNas is lagging waaay behind.

Plex latest release is Version 1.21.3.4021

but TrueNas is on Version: 1.21.1.3876

**Comment by MTCoster** [comment]
@kmoore134 Still no luck - any thoughts?

**Comment by kmoore134** [comment]
I'll take a look. Upstream sources look good, but perhaps the packages aren't building for some reason. Will poke at it and get back to the thread.

**Comment by kmoore134** [comment]
![image](https://user-images.githubusercontent.com/1933088/107647303-00658e00-6c49-11eb-84de-b03cbf7d86db.png)

Took a look, appears that the most recent updates just pushed into upstream FreeBSD sources a few days back. The packages tend to lag 7-10 days behind this. I'd expect to see the package updates sometime in the next couple days, probably over the weekend.
