### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by SmoochySix4** [freenas/iocage-ix-plugins#291]
Plex has an update. Is there anyway this can check and pull updates from Plex?

**Comment by CognitiveFeline** [comment]
nah they like to make sure the updates are passed from repo to repo, group to group for an endless cycle of delays so that way they can remind you that you need to keep your systems & software up-to-date to enjoy new features and fix bugs/security issues... the irony has never been lost on me just how extremely far behind freenas/truenas and their plugins get, just as you come up to an 'actual' "latest" cycle you know you're just getting caught up to last week. Despite all the capabilities of git and pkgs, in 2021 no less, that what should be simple to do (pick a genuine speed at to which you can grab and apply officially released versions... you get what they decide when the decide and don't ever get excited about a "latest" branch... those newspapers have been left out in the wind and rain a few weeks now :)

**Comment by sonicaj** [comment]
@SmoochySix4 you can click on update button available in the Plugins section and that will update the plugin. But to be clear, this will not necessarily pull the latest tagged version of plex, it will update to the latest version available in freebsd packages which might get updated less frequently. I'm closing this issue, please let me know if updating to latest available freebsd plex version does not work for you. Thank you :)
