### ISSUE TITLE
Errors related to PHP packages when installing plugins

### ISSUE THREAD

**Issue by Olivier-Roy** [freenas/iocage-ix-plugins#302]
Hello, I am running a fresh install of TrueNAS and I already installed a few plugins (Plex and MineOS). I also want to install Nextcloud and FAMP, but when I try to do so, I get these errors. Do you know what could be the problem? It seems to be related to PHP packages missing...

`Error: Nextcloud had a failure Exception: RuntimeError Message: pkg error: - nextcloud-php74 :,php74-pecl-imagick-im7 :,php74-bcmath :,php74-gmp :,php74-pcntl :,php74-pecl-redis : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed`

`Error: FAMP had a failure Exception: RuntimeError Message: pkg error: - php74 :,php74-mysqli :,mod_php74 : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed`

**Comment by Olivier-Roy** [comment]
As mentioned in [this reply](https://www.truenas.com/community/threads/can%E2%80%99t-fetch-php-7-4-artifacts-in-plugin-installation.97761/post-674858) on the forum, it looks like PHP 7.4 isn't available anymore.

**Comment by italocp04** [comment]
I am experiencing the same issue when installing the Nextcloud Plugin.

![TrueNAS-Nextcloud](https://user-images.githubusercontent.com/52760352/147711928-4f463acb-5967-401b-8de8-4d35d291d57d.jpg)

**Comment by dantedemian19** [comment]
Same here, with nextcloud plugin
![Screenshot (756)](https://user-images.githubusercontent.com/35985947/147712089-bad7d276-f940-440d-8fc0-fd6199cb0442.png)

**Comment by zhangwenyi** [comment]
Same errors here. My solution below:
1) open truenas shell
2) wget https://raw.githubusercontent.com/freenas/iocage-ix-plugins/master/nextcloud.json
3) change nextcloud.json, line 25 packagesite, replace "latest" with "quarterly"
4) iocage fetch -P ./nextcloud.json --name Nextcloud

**Comment by gstotzem** [comment]
@zhangwenyi thank you very much.
The installation ends with
```
Admin Portal:
http://xxx.xxx.xxx.xxx:8282
```
Opening in a browser i see a login screen, but i didn't get any information about the initial user/password :-(
Any idea where to find that detail?

**Comment by zhangwenyi** [comment]
@gstotzem 
Please check the file: /root/PLUGIN_INFO

**Comment by sasi202** [comment]
> Same errors here. My solution below:
> 
> 1. open truenas shell
> 2. wget https://raw.githubusercontent.com/freenas/iocage-ix-plugins/master/nextcloud.json
> 3. change nextcloud.json, line 25 packagesite, replace "latest" with "quarterly"
> 4. iocage fetch -P ./nextcloud.json --name Nextcloud

it doesnt work for me, I may not have done the instructions properly.
You can explain again more specifically?
i opened the shell and copy "wget https://raw.githubusercontent.com/freenas/iocage-ix-plugins/master/nextcloud.json"
now how can i change the file?

**Comment by tprelog** [comment]
> now how can i change the file?

Here's one way to edit the file
```
ee ./nextcloud.json
```

To save and exit, press <kbd>ESC</kbd> then press <kbd>ENTER</kbd> twice

**Comment by sasi202** [comment]
Ok i saved the file and what to do with the final step? Just copy to the shell and enter?

**Comment by tprelog** [comment]
> Ok i saved the file and what to do with the final step? Just copy to the shell and enter?

Yea. I _think_ that should do it

**Comment by sasi202** [comment]
Thanks for the fast respond but this solution didn't work for me. I'm still getting the same error.
any other ideas?

![Untitled](https://user-images.githubusercontent.com/96876541/147767074-e8f569aa-201a-4f9c-9589-add0ffcad541.png)

**Comment by tprelog** [comment]
@sasi202 - Sorry my friend, I just tested and it worked as expected. I'm not sure what else to do.

I can only say, double check the `nextcloud.json` file you edited. Make sure your changes were saved. And I guess, make sure you typed the command exactly as shown.  Sorry, I don't know what else to say

```
iocage fetch -P ./nextcloud.json --name Nextcloud
```

**Comment by funkybunch** [comment]
Is anyone aware of a way to upgrade an existing nextcloud jail?  Unless I'm missing something it seems like the workaround is only for fresh installs.  I'd like to not have to completely reconfigure nextcloud if at all possible.

**Comment by funkybunch** [comment]
Created #303.  If a release was cut with this config change, that should allow the plugin to be installed and updated while a PHP 8.0 version is tested.

Would love some input from the maintainers on this.

**Comment by tprelog** [comment]
> Is anyone aware of a way to upgrade an existing nextcloud jail? Unless I'm missing something it seems like the workaround is only for fresh installs.

I have a few ideas, not sure if they are good ones but they are ideas nonetheless.

**Option 1** - Edit the actual manifest your plugin will use while updating.
- replace `$ZPOOL` with the name of your zpool holding iocage
```
cd /mnt/$ZPOOL/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git
ee nextcloud.json
```

**Option 2** - Manually edit the pkg.conf inside your plugin, and just update like it was a non-plugin jail.
- replace `$JAIL` with the name of your nextcloud plugin
```
iocage console $JAIL
ee /etc/pkg/FreeBSD.conf
pkg update && pkg upgrade
```

**Option 3** - Merge your changes into the 12.2-RELEASE branch on your own fork, then tell plugin to use your fork.
- replace `$JAIL` with the name of your nextcloud plugin
```
iocage set plugin_repository=https://github.com/funkybunch/iocage-ix-plugins $JAIL
```

**Comment by hittheroadjack** [comment]
Just went through the enhancement of my FAMP installation to enable wordpress to run. It was a lengthy operation - obviously Wordpress does not run on a native apache24!
First make sure you have the apache extensions **mbstring, mySQL and session activated in httpd.conf, i.e. uncommented**. In my case mbstring was not even loaded - I had to **pkg install it from the jail FAMP shell**.
After that - step by step - I had to pkg install the following **php80 -Modules: -curl, -exif, -fileinfo, -pecl-imagick, -zip, -intl, -filler, -dom, -iconv, -zlib and -gd (the latter is absolutely necessary by request of wordpress)**.
Thereafter a normal wordpress install was possible and runs smoothly now on my TrueNAS FAMP server. I use it only for domestic development!
Now, I am not quite sure what happens if I loose my HD with the boot pool on it. Are all the jails and the extensive installations safe on starting with a new boot HD and load the latest config file?
As all installation happened in a jail, it should survive the exchange of the boot pool. 
Anyone to know?

**Comment by Silaslacasse** [comment]
Hi, I'm having the same issues... I try to run your script @hittheroadjack, but still have the same issues : 
![image](https://github.com/freenas/iocage-ix-plugins/assets/55695073/f207bb1b-7a48-4e7e-9f24-63f73b5216d8)

It looks like I can't run any PHP images using pkgs, but I'm still new on truenas, so I can't figure why

Any ideas ?

**Comment by gabrielegirardi** [comment]
the same problem

**Comment by hittheroadjack** [comment]
I could imagine two reasons for the problem:

1. FreeBSD has only a rudimentary pkg installed when fresh. To try out just give #pkg on the shell and you will be ask to install it completely. Read the documentation here : [https://docs.freebsd.org/en/books/handbook/ports/](url)
2. the packagesite has changed. Please change it to 'latest' instead of 'quarterly' in the script and try again

**Comment by Silaslacasse** [comment]
Thanks for the help @hittheroadjack  🙏 , 
I try to use pakagesite 'latest' with nextcloud-ph81 (because php80 wasn't working) and now I have the let's encrypt issue : 
<img width="681" alt="image" src="https://github.com/freenas/iocage-ix-plugins/assets/55695073/0e0f70b3-c92b-4caf-aa5b-088c5201ef9d">

any idea ?

**Comment by hittheroadjack** [comment]
What was the problem with php80? error messages?
To be frank, this is not a sophisticated workaround - FAMP is still based on php74.
I tried it and it worked for me.
What happens if you change further on to php81? I do not know! There are millions of possible incompatibilities.
I was kind of lucky that php80 worked for me and I do not have any clue what NextCloud-php81 does. It looks quite mixed up in your screenshot.

**Comment by ryoko90210** [comment]
Hi. I managed to solve this by changing all the php80 entries in the .json file to php81 like so.
        "nextcloud-php81",
        "php81-pecl-imagick-3.7.0_2",
        "php81-bcmath",
        "php81-gmp",
        "php81-pcntl",
        "php81-pecl-redis",
        "php81-phar",
I also changed the latest to quarterly on line25. Hope this works for others.
